# Generated by Django 6.0.1 on 2026-02-01 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consumidor', models.CharField(choices=[('PN', 'Persona Natural'), ('IP', 'Institución Pública'), ('EP', 'Empresa Privada')], max_length=2)),
                ('ci_nit', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('representante_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sector', models.CharField(max_length=100)),
                ('actividad', models.CharField(max_length=150)),
                ('municipio', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumidores_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
